[package]
name = "claws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# codecommit = { path = "src/codecommit.rs" }
# codebuild = { path = "src/codebuild.rs" }
